"""Subclass of MyFrame4, which is generated by wxFormBuilder."""

import wx
import sys_of_RSS

# Implementing MyFrame4
class sys_of_RSSMyFrame4( sys_of_RSS.MyFrame4 ):
	def __init__( self, parent ):
		sys_of_RSS.MyFrame4.__init__( self, parent )

if __name__ == '__main__':
	app = wx.App()

	sys_of_RSSMyFrame4(None).Show()

	app.MainLoop()