"""Subclass of MyFrame5, which is generated by wxFormBuilder."""

import wx
import sys_of_RSS

# Implementing MyFrame5
class sys_of_RSSMyFrame5( sys_of_RSS.MyFrame5 ):
	def __init__( self, parent ):
		sys_of_RSS.MyFrame5.__init__( self, parent )

if __name__ == '__main__':
	app = wx.App()

	sys_of_RSSMyFrame5(None).Show()

	app.MainLoop()