"""Subclass of MyFrame8, which is generated by wxFormBuilder."""

import wx
import sys_of_RSS
#from sys_of_RSSMyFrame9 import sys_of_RSSMyFrame9
from sys_of_RSSMyFrame6 import sys_of_RSSMyFrame6
# Implementing MyFrame8
class sys_of_RSSMyFrame8( sys_of_RSS.MyFrame8 ):
	def __init__( self, parent ,cursor):
		sys_of_RSS.MyFrame8.__init__( self, parent )
		print("MyFrame8 初始化完成")  # 调试信息
		self.cursor = cursor  # 存储 cursor 为实例变量 2025.06.14
		self.parent=parent###

	# Handlers for MyFrame8 events.
	def onCloseMainWindow( self, event ):
		# TODO: Implement onCloseMainWindow
		pass

	def personal_info( self, event ):
		# TODO: Implement personal_info
		#next_window = sys_of_RSSMyFrame9(None, title="个人信息管理")
		#next_window.Show()
		
		#self.Hide()  # 隐藏当前窗口
		pass

	def add_replenish( self, event ):
		# TODO: Implement add_replenish
		pass

	def add_order( self, event ):
		# TODO: Implement add_order
		pass

	def add_damage( self, event ):
		# TODO: Implement add_damage
		pass

	def employee_manage( self, event ):
		# TODO: Implement employee_manage
		print("员工管理按钮被点击")  # 调试信息

		print(self.m_button19.IsEnabled())  # 检查按钮是否启用
		print(self.m_button19.IsShown())    # 检查按钮是否显示

		child =sys_of_RSSMyFrame6(parent=self,cursor=self.cursor)####
		child.Show()
		#sys_of_RSS.MyFrame6(self, self.account_status).Show()
		pass

	def supplier_manage( self, event ):
		# TODO: Implement supplier_manage
		pass

	def item_manage( self, event ):
		# TODO: Implement item_manage
		pass

	def replenish_manage( self, event ):
		# TODO: Implement replenish_manage
		pass

	def order_manage( self, event ):
		# TODO: Implement order_manage
		pass

	def damage_manage( self, event ):
		# TODO: Implement damage_manage
		pass

	def exit( self, event ):
		# TODO: Implement exit
		pass