"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import sys_of_RSS

import pymysql

# Implementing MyFrame1
class sys_of_RSSMyFrame1( sys_of_RSS.MyFrame1 ):
	def __init__( self, parent ):
		sys_of_RSS.MyFrame1.__init__( self, parent )

		# 数据库连接参数（实际使用时建议使用输入框）
		self.db_config = {
            'host': 'localhost',
            'user': 'root',
            'password': '1111',
            'database': 'grocery_sys',
            'charset': 'utf8mb4'
        }

	# Handlers for MyFrame1 events.
	def login( self, event ):
		# TODO: Implement login
		
		try:
			login_name=self.m_textCtrl1.GetValue()
			password=self.m_textCtrl2.GetValue()
            # 建立数据库连接
			connection = pymysql.connect(**self.db_config)
			cursor = connection.cursor()
			#k=-1##登录状态
			try:
				cursor.execute("SELECT password FROM employee WHERE name = %s", (login_name,))#避免注入风险
				real_password=cursor.fetchall()[0][0]
				print(real_password)
				if password==real_password:
					self.m_textCtrl1.Clear()
					self.m_textCtrl2.Clear()
					self.m_textCtrl12.SetValue("登录成功!")
					child =sys_of_RSS.MyFrame8(parent=self)
					child.Show()
					#k=1
				else:
					#k=0
					self.m_textCtrl12.SetValue("密码错误！")
			except:
				self.m_textCtrl12.SetValue("用户名不存在！")
			
		except pymysql.Error as e:
			wx.MessageBox(f"数据库错误: {e}", "错误", wx.OK | wx.ICON_ERROR)
			print("数据库连接错误！")
		

		
		'''
		finally:
            # 关闭连接
			if 'connection' in locals() and connection.open:
				cursor.close()
				connection.close()
		'''	
		
		pass

	def gotosignup( self, event ):
		# TODO: Implement sign_in
		child =sys_of_RSS.MyFrame3(parent=self)
		child.Show()
		pass

	def logclear( self, event ):
		# TODO: Implement logclear

		pass


if __name__ == '__main__':



	app = wx.App()

	sys_of_RSSMyFrame1(None).Show()

	app.MainLoop()