"""Subclass of MyFrame7, which is generated by wxFormBuilder."""

import wx
import sys_of_RSS

# Implementing MyFrame7
class sys_of_RSSMyFrame7( sys_of_RSS.MyFrame7 ):
	def __init__( self, parent ):
		sys_of_RSS.MyFrame7.__init__( self, parent )
if __name__ == '__main__':
	app = wx.App()

	sys_of_RSSMyFrame7(None).Show()

	app.MainLoop()