"""Subclass of MyFrame6, which is generated by wxFormBuilder."""

import wx
import sys_of_RSS

# Implementing MyFrame6
class sys_of_RSSMyFrame6( sys_of_RSS.MyFrame6 ):
	def __init__( self, parent ):
		sys_of_RSS.MyFrame6.__init__( self, parent )

