"""Subclass of MyFrame3, which is generated by wxFormBuilder."""

import wx
import sys_of_RSS

# Implementing MyFrame3
class sys_of_RSSMyFrame3( sys_of_RSS.MyFrame3 ):
	def __init__( self, parent ):
		sys_of_RSS.MyFrame3.__init__( self, parent )

	# Handlers for MyFrame3 events.
	def signup( self, event ):
		# TODO: Implement signup
		logup_name=self.m_textCtrl9.GetValue()
		logup_place=self.m_textCtrl11.GetValue()
		logup_password=self.m_textCtrl10.GetValue()
		logup_password=self.m_textCtrl12.GetValue()
		pass

	def quit_action( self, event ):
		# TODO: Implement quit_action
		pass


